//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALBAITAR_Softvet.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Last_login_user_idx {
            get {
                return ((int)(this["Last_login_user_idx"]));
            }
            set {
                this["Last_login_user_idx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Last_login_is_admin {
            get {
                return ((bool)(this["Last_login_is_admin"]));
            }
            set {
                this["Last_login_is_admin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool App_Closed_By_User {
            get {
                return ((bool)(this["App_Closed_By_User"]));
            }
            set {
                this["App_Closed_By_User"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RANCOSOFT_GMAIL_AUTHENT {
            get {
                return ((string)(this["RANCOSOFT_GMAIL_AUTHENT"]));
            }
            set {
                this["RANCOSOFT_GMAIL_AUTHENT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Use_animals_logo {
            get {
                return ((bool)(this["Use_animals_logo"]));
            }
            set {
                this["Use_animals_logo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Last_login_user_full_nme {
            get {
                return ((string)(this["Last_login_user_full_nme"]));
            }
            set {
                this["Last_login_user_full_nme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Login_Auto_Enter {
            get {
                return ((bool)(this["Login_Auto_Enter"]));
            }
            set {
                this["Login_Auto_Enter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1900-01-01")]
        public global::System.DateTime Last_entred_date_by_Auto_Enter {
            get {
                return ((global::System.DateTime)(this["Last_entred_date_by_Auto_Enter"]));
            }
            set {
                this["Last_entred_date_by_Auto_Enter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Maximize_Main_Frm {
            get {
                return ((bool)(this["Maximize_Main_Frm"]));
            }
            set {
                this["Maximize_Main_Frm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Faire_consom_stock_apres_vente {
            get {
                return ((bool)(this["Faire_consom_stock_apres_vente"]));
            }
            set {
                this["Faire_consom_stock_apres_vente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Faire_reg_espece_facture_vente {
            get {
                return ((bool)(this["Faire_reg_espece_facture_vente"]));
            }
            set {
                this["Faire_reg_espece_facture_vente"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.ACE.OLEDB.12.0;Data Source=|DataDirectory|\\DB_TMP.accdb")]
        public string DB_TMPConnectionString {
            get {
                return ((string)(this["DB_TMPConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Main_Frm_Tabs_Horientation_Is_Verticatl {
            get {
                return ((bool)(this["Main_Frm_Tabs_Horientation_Is_Verticatl"]));
            }
            set {
                this["Main_Frm_Tabs_Horientation_Is_Verticatl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string Connection_String_IP_Or_LocalHost {
            get {
                return ((string)(this["Connection_String_IP_Or_LocalHost"]));
            }
            set {
                this["Connection_String_IP_Or_LocalHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Connection_String_PC_name {
            get {
                return ((string)(this["Connection_String_PC_name"]));
            }
            set {
                this["Connection_String_PC_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("--")]
        public string Codified_Activate_Code {
            get {
                return ((string)(this["Codified_Activate_Code"]));
            }
            set {
                this["Codified_Activate_Code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Codifed_Activation_Email {
            get {
                return ((string)(this["Codifed_Activation_Email"]));
            }
            set {
                this["Codifed_Activation_Email"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Codified_Act_Command_dmnd_date {
            get {
                return ((string)(this["Codified_Act_Command_dmnd_date"]));
            }
            set {
                this["Codified_Act_Command_dmnd_date"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Codified_Act_Clt_Tel {
            get {
                return ((string)(this["Codified_Act_Clt_Tel"]));
            }
            set {
                this["Codified_Act_Clt_Tel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Codified_Act_Clt_Nme {
            get {
                return ((string)(this["Codified_Act_Clt_Nme"]));
            }
            set {
                this["Codified_Act_Clt_Nme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime Last_Auto_Buckup_Date {
            get {
                return ((global::System.DateTime)(this["Last_Auto_Buckup_Date"]));
            }
            set {
                this["Last_Auto_Buckup_Date"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Restarted_for_login_lock {
            get {
                return ((bool)(this["Restarted_for_login_lock"]));
            }
            set {
                this["Restarted_for_login_lock"] = value;
            }
        }
    }
}
