//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALBAITAR_Softvet.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Last_login_user_idx {
            get {
                return ((int)(this["Last_login_user_idx"]));
            }
            set {
                this["Last_login_user_idx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Last_login_is_admin {
            get {
                return ((bool)(this["Last_login_is_admin"]));
            }
            set {
                this["Last_login_is_admin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool App_Closed_By_User {
            get {
                return ((bool)(this["App_Closed_By_User"]));
            }
            set {
                this["App_Closed_By_User"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RANCOSOFT_LAST_USED_DATE {
            get {
                return ((string)(this["RANCOSOFT_LAST_USED_DATE"]));
            }
            set {
                this["RANCOSOFT_LAST_USED_DATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RANCOSOFT_LAST_DEVICE_NAME {
            get {
                return ((string)(this["RANCOSOFT_LAST_DEVICE_NAME"]));
            }
            set {
                this["RANCOSOFT_LAST_DEVICE_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RANCOSOFT_LAST_ACT_VERIF_DAYS_NB {
            get {
                return ((int)(this["RANCOSOFT_LAST_ACT_VERIF_DAYS_NB"]));
            }
            set {
                this["RANCOSOFT_LAST_ACT_VERIF_DAYS_NB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RANCOSOFT_LAST_ACT_VERIF_DATE {
            get {
                return ((string)(this["RANCOSOFT_LAST_ACT_VERIF_DATE"]));
            }
            set {
                this["RANCOSOFT_LAST_ACT_VERIF_DATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RANCOSOFT_CLIENT_KEY {
            get {
                return ((string)(this["RANCOSOFT_CLIENT_KEY"]));
            }
            set {
                this["RANCOSOFT_CLIENT_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RANCOSOFT_ACTIVE_CODE_ID {
            get {
                return ((int)(this["RANCOSOFT_ACTIVE_CODE_ID"]));
            }
            set {
                this["RANCOSOFT_ACTIVE_CODE_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RANCOSOFT_GMAIL_AUTHENT {
            get {
                return ((string)(this["RANCOSOFT_GMAIL_AUTHENT"]));
            }
            set {
                this["RANCOSOFT_GMAIL_AUTHENT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Use_animals_logo {
            get {
                return ((bool)(this["Use_animals_logo"]));
            }
            set {
                this["Use_animals_logo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Last_login_user_full_nme {
            get {
                return ((string)(this["Last_login_user_full_nme"]));
            }
            set {
                this["Last_login_user_full_nme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Login_Auto_Enter {
            get {
                return ((bool)(this["Login_Auto_Enter"]));
            }
            set {
                this["Login_Auto_Enter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1900-01-01")]
        public global::System.DateTime Last_entred_date_by_Auto_Enter {
            get {
                return ((global::System.DateTime)(this["Last_entred_date_by_Auto_Enter"]));
            }
            set {
                this["Last_entred_date_by_Auto_Enter"] = value;
            }
        }
    }
}
